---
- name: Update PiHole
  ansible.builtin.shell: PIHOLE_SKIP_OS_CHECK=true pihole -up
  register: pihole_update_result
  changed_when: "'Everything is up to date!' not in pihole_update_result.stdout"
