---
- name: Converge
  hosts: all
  # become: true
  pre_tasks:
    - name: Ensure EPEL is enabled
      ansible.builtin.dnf:
        name: epel-release
        state: present
      when:
        - ansible_os_family == "RedHat"

    - name: Install curl on Rocky
      ansible.builtin.dnf:
        name: curl
        allowerasing: true
        state: present
      when:
        - ansible_os_family == "RedHat"

    - name: Enable universe repo (Ubuntu only)
      ansible.builtin.command: add-apt-repository -y universe
      when: ansible_distribution == "Ubuntu"
      become: true
      changed_when: false

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: ../../../.
